### PR TITLE
Page using reference created

### LINKED ISSUE #243: Create a section of page like the image given. (Using Next js)
### Description

image

Make 6 cards instead of 3 cards and match the background color with the website theme. (https://techsquadcommunity.tech/)

### Domain

Open Source

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

### PR DESCRIPTION
**Pull request by piyusha2001**
## 🛠️ Issue #243

Closes #243

## 👨‍💻 Changes proposed

Created a technology page as given in the issue . Styled acc to websites theme.
Page can be found at : http://localhost/:/technology
->Responsiveness handled using bootstrap
->Raw/Sample data can be found in Data folder

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

https://user-images.githubusercontent.com/81703477/170978016-1b97c48e-9f1e-420b-8fac-f7bddd5a1189.mp4

### CODE REVIEW

**Comment by piyusha2001** [comment]
@JaynouOliver  please review my PR

**Comment by JaynouOliver** [comment]
@piyusha2001 good to go, make the cards black please

**Comment by piyusha2001** [comment]
> @piyusha2001 good to go, make the cards black please

@JaynouOliver  Done . please check once.

**Comment by JaynouOliver** [comment]
reviewing

**Comment by JaynouOliver** [comment]
Merged! @piyusha2001 Thank you for working with TS Comm!

**Pull request merged**
