### PR TITLE
Fixed footer in mobile version of website

### LINKED ISSUE #135: Fix footer in the mobile version of the website
image

Fix the footer of the website. Let me give you an explanation, when we shift to the mobile version of the website, all the links and divs should be center aligned.  Some discussion is required regarding the alignment and other areas, make sure you connect with the mentors or project admin so that you can be guided! 
Thank you!

### PR DESCRIPTION
**Pull request by sohan2503001**
## 🛠️ Issue (135)

Closes #135

## 👨‍💻 Changes proposed

 Fixed footer in mobile version of website

## ✔️ Check List (Check all the applicable boxes) 

- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by ronitblenz** [comment]
It has merge conflicts... please fix them

**Comment by ronitblenz** [comment]
You have bugged the ABOUT CONTACT and LOGIN page footers... check
Screenshot 2022-03-27 at 5 45 43 PM

**Comment by sohan2503001** [comment]
Should i close the PR and make new one by doing required changes

**Comment by ronitblenz** [comment]
Yes

**Pull request closed without merging**
