### PR TITLE
Resource Page created

### LINKED ISSUE #125: Create a new Resource Page
### Description

I see that the resource page hasn't been made yet, so I can make it!

image

The above image is sample of what this page may include

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

### PR DESCRIPTION
**Pull request by Kumar-laxmi**
**THIS IS UNDER GSSoC'22**

## 🛠️ Issue (Number)

Closes #125 

## 👨‍💻 Changes proposed
- Creation of Resource Page

## ✔️ Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
Any one who wants to contribute more to this page can include more cards to it

## 📷 Screenshots
image
image

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
Oh I think I left some inputs by mistake, don't merge now

**Comment by Kumar-laxmi** [comment]
Yeah now you can check and merge

**Comment by ronitblenz** [comment]
The Upcoming events button is different from the rest of the pages... plz change it to what it is on other pages too

**Comment by Kumar-laxmi** [comment]
Now check it

**Comment by Kumar-laxmi** [comment]
I have resolved that problem too

**Comment by ronitblenz** [comment]
Another thing, in some cards the read more button is colliding with the floor, simply shorten the descriptive text... not much work required

**Comment by Kumar-laxmi** [comment]
Bro check now and if there are minor issues then just ignore it

**Comment by ronitblenz** [comment]
Screenshot 2022-03-12 at 5 24 53 PM

Make a Permanent Solution for this

**Comment by Kumar-laxmi** [comment]
Wait I will try

**Comment by Kumar-laxmi** [comment]
Bro check now

**Comment by Kumar-laxmi** [comment]
Screenshot 2022-03-12 at 6 10 11 PM

**Comment by ronitblenz** [comment]
Screenshot 2022-03-12 at 6 15 07 PM

The back to top button is over riding, and still few read more has same issue ... fix them

**Comment by Kumar-laxmi** [comment]
yeah ok

**Comment by Kumar-laxmi** [comment]
Bro the thing is now my Exams are going on so can you merge it for now, maybe in future some one can resolve the button  over ridding part.

Pls!

And for next couple of weeks I might be less active

**Comment by ronitblenz** [comment]
Sure.. Thanks for the contributions

**Comment by Kumar-laxmi** [comment]
Thanks for consideration

**Pull request merged**
