### PR TITLE
#about page enhance

### PR DESCRIPTION
**Pull request by akki251**
Fresh PR created @r3yc0n1c  
Issue #118

### CODE REVIEW

**Comment by ronitblenz** [comment]
Have you fetched and merged the dev branch? the previous commits of other contributors are still not visible

**Comment by akki251** [comment]
I just pull the changed from dev branch to my dev branch !

**Comment by akki251** [comment]
I can see changes  from previous commits ! 
image

**Comment by akki251** [comment]
These is the graph 
image

**Comment by ronitblenz** [comment]
Ok lets try to merge it...and if it has any issue... We will sort it out tomorrow

**Comment by ronitblenz** [comment]
And ... congo..its working well and good👍

**Comment by akki251** [comment]
Great , Please close Issue #118

**Pull request merged**
