### PR TITLE
Issue #80

### LINKED ISSUE #80: Shadow effect under the main vector when cursor hovers
### Description

Screenshot 2022-03-02 at 8 47 44 PM

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

### PR DESCRIPTION
**Pull request by HarshKumarChoudary**
## 👨‍💻 Changes proposed
Added the Shadow effect to the main vector at landing page. Hence Modified index.html and style.css.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by ronitblenz** [comment]
Screenshot 2022-03-04 at 11 40 27 AM
This svg is a transparent one, you have added the shadow to the whole div. You should make it like each element having shadows... Just apply this effect on the image itself.. thats it

**Comment by HarshKumarChoudary** [comment]
ok. I will fix that.

**Comment by HarshKumarChoudary** [comment]
Created Shadow effect on SVG image and removed box like look.

**Comment by ronitblenz** [comment]
Its looking fabbbb✨
Merging the PR

**Pull request merged**
