### PR TITLE
Improved About page by adding content in cards

### LINKED ISSUE #96: About page can be improved.
### Description

About page can be improved by placing member's images in decent card which resemble to cards in home page.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

### PR DESCRIPTION
**Pull request by AdnanMuzavor**
## 🛠️ Issue #96 

Closes #96 

## ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [✔️ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

->Placed members content in card which looks similar to cards on home page
->Align content/cards center for all devices
->Card on hovering expands
->On hovering image both image and card shall expand
->Responsive on all devices as shown in demo. 

## 📷 Screenshots
->It's a screen recording of how hover effects work and also showcases responsiveness.
Link:  https://www.recordjoy.com/view/SyLtAKyadrHGUySDedoH

### CODE REVIEW

**Comment by ronitblenz** [comment]
4th card should be on the same row...  You can fix that and make a PR

**Comment by AdnanMuzavor** [comment]
@ronitblenz I was actually trying that, but in that case all cards are aligning them selves intact which is not looking good. Abd when I am applying margin 4th one is automatically placed down although "col-lg-3/col-md-3", yes it's due to margin ,but if I don't give margin it'll look like this which you might not like:

 https://ibb.co/fp2Qfrn

**Comment by ronitblenz** [comment]
Ok got it... 
Thanks for your Contributor✨

**Comment by AdnanMuzavor** [comment]
Thank you for understanding bro.

**Pull request merged**
