### PR TITLE
Cover page and navbar updated

### PR DESCRIPTION
**Pull request by 19arnab190201**
## 👨‍💻 Changes proposed

1. Updated complete cover page
2. Added animations in cover page
3. fixed Navbar issue
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### BEFORE (FULL PAGE)
TechSquad Community (2)

### AFTER
BQor7vFM_4x

### BEFORE (MOBILE SCREEN)
TechSquad Community (3)

TechSquad Community (5)

### CODE REVIEW

**Comment by ronitblenz** [comment]
image

Thanks alot for your Contribution
Do you want to make such animations in the other pages too? It would be awesome

**Comment by 19arnab190201** [comment]
> image
> 
> Thanks alot for your Contribution Do you want to make such animations in the other pages too? It would be awesome

Ya sure , could you please show where ?

**Comment by ronitblenz** [comment]
Ping me ronitblenz#6939
on discord

lets discuss

**Comment by 19arnab190201** [comment]
> Ping me ronitblenz#6939 on discord
> 
> lets discuss

Done

**Pull request merged**
