### PR TITLE
fixed the bug in login page

### PR DESCRIPTION
**Pull request by codingkush**
fixed the bug in login page for mobile view and  hidden elements...

pppp

### CODE REVIEW

**Comment by codingkush** [comment]
fixed hidden elements

hdf

**Comment by codingkush** [comment]
Is this okay??

**Comment by JaynouOliver** [comment]
@codingkush the codes have changed a bit, please make fetch upstream and redo the pr, else everything is fine

**Comment by JaynouOliver** [comment]
closing this PR

**Pull request closed without merging**
