### PR TITLE
Sohan

### LINKED ISSUE #1: Change background color of cards
image

Change the background color according to the color of the tags.

### PR DESCRIPTION
**Pull request by sohan2503001**
## 🛠️ Issue (1)

Closes #1

## 👨‍💻 Changes proposed

- Change background color of cards

## ✔️ Check List (Check all the applicable boxes) 

- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Screenshot (290)

### CODE REVIEW

**Comment by ronitblenz** [comment]
The deployment failed again... I will look into the matter... Plz wait..

**Comment by sohan2503001** [comment]
okk

**Comment by sohan2503001** [comment]
Should make i make different branch and add new commits to it

**Comment by ronitblenz** [comment]
Yes plz do that once

**Pull request closed without merging**
