### PR TITLE
#129 Issue : Adding animation on social links

### LINKED ISSUE #129: Adding animation on social links
### Description

- The social links is looking fine, but adding animation to them adds additional effect to it.
- This feature will help increase User Interface(UI) of your website.
- Please assign me on this issue under GSSOC 22.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

### PR DESCRIPTION
**Pull request by TG922**
## 🛠️ Issue (Number)

Closes #129

## 👨‍💻 Changes proposed

Added Animation to the social links on hover.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

Image41

### CODE REVIEW

**Comment by ronitblenz** [comment]
Please align the text in the middle and change the bg colour of the banner which is opening after opening... 
Change the color to #12C6FF (Blue)

**Comment by TG922** [comment]
- [x] 1. Make a gap between the logos.
- [x] 2. Please align the text in the middle.
- [x] 3. change the bg colour of the banner which is opening after opening...  Change the colour to #12C6FF (Blue).
- [x] 4. Dont fade the social icons... keep them opaque, Rather keep the original colour scheme


- [ ] Make a gap between the paragraph, **Please assign this issue to someone else**.

- [x] I have added animation, which was my task. And also made most of the requested changes.

**Comment by ronitblenz** [comment]
You missed the rest of the pages, do the same changes for all the pages footer

**Comment by ronitblenz** [comment]
Btw its looking good... make the same changes in all the footers

**Comment by TG922** [comment]
Ok I will do it today I was having exam

**Comment by ronitblenz** [comment]
You have some branch conflicts too... resolve them while making updated PR

**Comment by TG922** [comment]
OK I'm on it will send PR within some hour

**Comment by ronitblenz** [comment]
You need to make the same animated links on all the page's footer
I hope you got my point...

**Comment by TG922** [comment]
> You need to make the same animated links on all the page's footer I hope you got my point...

Yes, I have already done changes.
I was facing an error while uploading the committed changes to this branch so I created another one that is working fine. I have already sent PR to that branch.

**Pull request closed without merging**
