### PR TITLE
Enhanced the display

### PR DESCRIPTION
**Pull request by Anushka-2003**
I have visualized the display of cards, buttons, and images.

### CODE REVIEW

**Comment by ronitblenz** [comment]
Solve the Merge conflicts by forking again and make the changes

**Comment by ronitblenz** [comment]
@Anushka-2003 Please solve the Merge Conflicts,
You need to fork the project again and make changes to the code by copying it from the code changes you made.
 I will merge the PR as soon as its resolved.

**Comment by Anushka-2003** [comment]
@ronitblenz Do I need to make the same changes again?

**Comment by JaynouOliver** [comment]
@Anushka-2003 connect with me on discord, need to solve your merge conflict.

**Comment by Anushka-2003** [comment]
tech dev channel is not anymore visible on GSSOC discord I am unable to
connect with you.

**Comment by JaynouOliver** [comment]
Subhro#8287

**Pull request merged**
