### PR TITLE
Changed background color of cards

### LINKED ISSUE #1: Change background color of cards
image

Change the background color according to the color of the tags.

### PR DESCRIPTION
**Pull request by sohan2503001**
issue<1>

## 🛠️ Issue

Closes #1

## 👨‍💻 Changes proposed

- Change background color of cards 

## ✔️ Check List (Check all the applicable boxes) 

- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Screenshot (287)

### CODE REVIEW

**Comment by ronitblenz** [comment]
Keeping the same shades.. can you make the colour lighter? It should just have the tinge of those colours

**Comment by sohan2503001** [comment]
yes, any other changes

**Comment by ronitblenz** [comment]
> yes, any other changes

Nothing as such, just it should look translucent... I guess you got the feel... just replace the white colour of the old cards with the colour in tags (light tinge of those colours)..  The tag and text colour should be as it was in the old card

**Comment by sohan2503001** [comment]
Is it okk now

Screenshot (288)

**Comment by ronitblenz** [comment]
> Is it okk now
> 
> Screenshot (288)
> 

It should be lighter... It should just contain the essence of the colour....

**Comment by sohan2503001** [comment]
Screenshot (290)

**Comment by ronitblenz** [comment]
> 
> Screenshot (290)
> 
> 

Perfect 💓... You did an awesome job.... Make a PR

**Comment by ronitblenz** [comment]
Push the commits .. I will merge the PR

**Comment by sohan2503001** [comment]
Yes Yes , Thank you

**Comment by ronitblenz** [comment]
Why its showing deployment failed?... You can do one thing... I am closing this PR... Make a new pr from fresh after balancing the dev branch

**Pull request closed without merging**
