### PR TITLE
Added Header & Footer in LogIn page

### LINKED ISSUE #117: Add Header and Footer in LogIn page
### Description

In LogIn page we can see that their is no Header and Footer which makes navigation difficult to other pages.

image

In above image we can see that the header and footer are missing.

Also apart from this the page is also missing icon near title.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

### PR DESCRIPTION
**Pull request by Kumar-laxmi**
**THESE CHANGES ARE UNDER GSSoC'22**

## 🛠️ Issue (Number)

Closes #117 

## 👨‍💻 Changes proposed
- Header and Footer creation in log in page
- Code Optimization of various JS functions

## ✔️ Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Nothing particular to this PR

## 📷 Screenshots
HEADER
Screenshot 2022-03-07 at 4 18 11 PM

FOOTER
Screenshot 2022-03-07 at 4 18 22 PM

### CODE REVIEW

**Comment by ronitblenz** [comment]
You forgot to do it for the registration page, do it then make a PR

**Comment by Kumar-laxmi** [comment]
ohk my bad

**Comment by Kumar-laxmi** [comment]
I will do that too

**Comment by Kumar-laxmi** [comment]
Header in Registration Page
image


Footer in Registration Page
image

**Comment by Kumar-laxmi** [comment]
I think there is nothing more to do

**Comment by Kumar-laxmi** [comment]
Shit I think I messed some property

**Comment by Kumar-laxmi** [comment]
Ah I will resolve this too

**Comment by Kumar-laxmi** [comment]
image

Bro is this ok

**Comment by Kumar-laxmi** [comment]
I have changed the design

**Comment by Kumar-laxmi** [comment]
Should I make a commit with this

**Comment by ronitblenz** [comment]
Have you made the registation page like this only? if so plz send a screenshot

**Comment by Kumar-laxmi** [comment]
yeah wait I am making it
 do you like this design

**Comment by Kumar-laxmi** [comment]
image

Yeah done

**Comment by ronitblenz** [comment]
Yes, just change the continue with facebook to continue with google
and continue with twitter to continue with github

And also, it seems to be a bit tilted, fix that too

**Comment by Kumar-laxmi** [comment]
This one registration

**Comment by Kumar-laxmi** [comment]
Should I commit new changes to this PR

**Comment by ronitblenz** [comment]
> This one registration

Gotcha

**Comment by ronitblenz** [comment]
> Should I commit new changes to this PR

Make the changes then make commit, and also, include register with google and github

**Comment by Kumar-laxmi** [comment]
No I don't think it is tilted

**Comment by ronitblenz** [comment]
The twiiter button is shifted a bit

> image
> 
> Bro is this ok

**Comment by Kumar-laxmi** [comment]
image
 Oh shit actually that is older one

**Comment by Kumar-laxmi** [comment]
This is the changed one

**Comment by ronitblenz** [comment]
> This is the changed one

Cool, where is the google and github login ?
Github and google register is also needed in Registration

**Comment by Kumar-laxmi** [comment]
yeah I will include that and make a commit to this PR

**Comment by ronitblenz** [comment]
Make sure its responsive for small devices too (like smartphones)

**Comment by Kumar-laxmi** [comment]
YEAH OK

**Comment by Kumar-laxmi** [comment]
Log In
image

Register Page
image

**Comment by Kumar-laxmi** [comment]
Now is it ok

**Comment by Kumar-laxmi** [comment]
And bro if you mind changing this issue and PR to Level-3

**Comment by Kumar-laxmi** [comment]
Cuz I had to remove the previous one and re-design the whole thing

**Comment by ronitblenz** [comment]
> Log In image
> 
> Register Page image

You by mistake made 3 input boxes instead of 4... in the registration page... see carefully

**Comment by ronitblenz** [comment]
And also, it has some branch conflicts fix them

**Comment by Kumar-laxmi** [comment]
Bro now this is merge conflict free

And this is what I have changed
image

**Comment by ronitblenz** [comment]
Screenshot 2022-03-08 at 12 44 23 PM

The head of the vector and the email box is overriden by the nav bar

**Comment by Kumar-laxmi** [comment]
Screenshot 2022-03-08 at 1 32 45 PM
 Now check

**Comment by Kumar-laxmi** [comment]
Is it ok now?

**Comment by ronitblenz** [comment]
Great

**Pull request merged**
