### PR TITLE
The UI for Forgot Password Page Created

### LINKED ISSUE #149: Create a Forgot Password Page
**THIS IS UNDER GSSoC'22**

### Description

We can create a Forgot Password Page and link to the anchor tag in LogIn.html

image

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

### PR DESCRIPTION
**Pull request by Kumar-laxmi**
## 🛠️ Issue (Number)

Closes #149 

## 👨‍💻 Changes proposed
- Create a Forgot Password Page
- Link it to index.html
- Maintain website template design in this page

## ✔️ Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
There is nothing relevant for this issue/pull request

## 📷 Screenshots
image

### CODE REVIEW

**Comment by ronitblenz** [comment]
It should have a criteria for "Last used Password"
I hope it makes sense

**Comment by Kumar-laxmi** [comment]
image

Bro this is the standard format used.

If we include "Last used password" then won't it reveal your current password to anyone?

**Comment by ronitblenz** [comment]
There is a validation code thing, like an otp

**Comment by ronitblenz** [comment]
Ok let it be... merging the PR

**Pull request merged**
