### PR TITLE
#167 Blog Page Created

### LINKED ISSUE #167: Create the Blog Page
### Description

Here is the UI Design for the Blog page

https://github.com/Tech-Squad-Community/techsquad-community-website/tree/dev/UI

And also, use your creativity if you want
Happy Coding✨

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

### PR DESCRIPTION
**Pull request by Kumar-laxmi**
## 🛠️ Issue (Number)

Closes #167 

## 👨‍💻 Changes proposed
- Created Blog PAGE
- Link it to index.html
- Update Font-Awesome library

## ✔️ Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
This design can be modified further

## 📷 Screenshots
image
image

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
@ronitblenz Bro what sort of advancement should I do in UI

**Comment by ronitblenz** [comment]
I mean we can improve the colour schemes... And also, the fonts can be changed... Its looking very un professional dont you think?..

Do some creative stuffs... Try something new

**Comment by Kumar-laxmi** [comment]
Yeah the Blog Page looks really unprofessional but since you gave a design so I implemented it.

Like if you can please send a picture of the design that you want.

**Comment by Kumar-laxmi** [comment]
@ronitblenz Bro how about the design below :
Screenshot 2022-03-30 at 2 34 22 PM
Screenshot 2022-03-30 at 2 34 15 PM
Screenshot 2022-03-30 at 2 34 11 PM

**Comment by ronitblenz** [comment]
I liked that design 
https://fullstackstage.com/introducing-supertokens-the-open-source-auth-alternative-that-is-easy-to-self-host

and here is the template you can follow... 
Screenshot 2022-03-30 at 2 43 05 PM
Screenshot 2022-03-30 at 2 43 23 PM

**Comment by Kumar-laxmi** [comment]
@ronitblenz  Bro but this page looks more like a resource page

**Comment by ronitblenz** [comment]
Ok do one thing... Take the idea from both

**Comment by Kumar-laxmi** [comment]
Ok

**Comment by Kumar-laxmi** [comment]
@ronitblenz Bro just have a look at the Blog Page
image

**Comment by Kumar-laxmi** [comment]
This is more of a professional look

**Comment by Kumar-laxmi** [comment]
@ronitblenz Please check once
image
image

**Comment by ronitblenz** [comment]
Great work ✨

**Pull request merged**
